### ISSUE TITLE
feat: support sort when multiple tags found

### ISSUE THREAD

**Issue by sysulq** [srikrsna/protoc-gen-gotag#38]
<img width="1248" alt="截屏2023-02-07 10 53 12" src="https://user-images.githubusercontent.com/1734615/217136261-b3a35c4b-bf59-4338-8433-81b9c088dfff.png">

At present, there is a problem. When there are multiple tags, the random order will cause changes when regenerating the code, even if the proto file is not modified.

**Comment by Kavuti** [comment]
Is this issue still relevant? 
Me, @ucpr and @mesmerx are embracing the project and planning both maintenance and evolution, so we would like to tidy up everything before working on new features. If the issue is not relevant anymore or we don't get a response in a few days, it will be closed, until we are ready to work on it.

**Comment by sysulq** [comment]
Seems like it's ok now, will reopen when reproduced.
