### ISSUE TITLE
Support to auto add custom tag options fields

### ISSUE THREAD

**Issue by PramodChaitanyakvv** [srikrsna/protoc-gen-gotag#41]
The current library supports adding custom tags automatically but doesn't support auto adding custom tag options automatically. Can we add the following feature to auto add custom tag options along with custom tags?

Current library support:

```
execution of this command will generate following structs

protoc -I /usr/local/include \
    	-I . \
    	--gotag_out=auto="form-as-camel":. example/example.proto
  

Generated Go structs
  
type Foo struct {
	Id   string `form:"id"`
	Name string `form:"name"`
	Age  int    `form:"age"`
}
```	
  
   

 Requested feature
 
 
```
auto add custom tag options to "form" tag in above struct
 
Expected Generated Go structs
 
type Foo struct {
	Id   string `form:"id,omitempty,optional"`
	Name string `form:"name,omitempty,optional"`
	Age  int    `form:"age,omitempty,optional"`
}
```

**Comment by Kavuti** [comment]
Is this issue still relevant? 
Me, @ucpr and @mesmerx are embracing the project and planning both maintenance and evolution, so we would like to tidy up everything before working on new features. If the issue is not relevant anymore or we don't get a response in a few days, it will be closed, until we are ready to work on it.

**Comment by Kavuti** [comment]
The issue will be closed due to inactivity. It may be reopened in the future when the rework will be stable.
